/**
 * Export service — generate downloadable PDF and PNG from TAB content.
 * Uses PDFKit for PDF; PNG is rendered via a minimal inline SVG rasterization approach.
 */

const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');
const config = require('../config');
const { ensureDir } = require('../utils/fileUtils');
const logger = require('../utils/logger');

/** Monospace font stack for tab rendering */
const TAB_FONT = 'Courier';
const TAB_FONT_SIZE = 11;
const TITLE_FONT_SIZE = 18;
const MARGIN = 50;

/**
 * @typedef {object} ExportOptions
 * @property {string} ascii - TAB ascii content
 * @property {object} meta - Title, composer, etc.
 * @property {string} jobId - Unique export identifier
 */

/**
 * Export TAB as PDF file.
 * @param {ExportOptions} options
 * @returns {Promise<string>} Path to generated PDF
 */
async function exportToPdf(options) {
  const { ascii, meta, jobId } = options;
  const exportDir = path.join(config.paths.outputDir, jobId, 'exports');
  ensureDir(exportDir);

  const pdfPath = path.join(exportDir, `${sanitizeFilename(meta.title || 'tabify-tab')}.pdf`);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'LETTER',
      margins: { top: MARGIN, bottom: MARGIN, left: MARGIN, right: MARGIN },
      info: {
        Title: meta.title || 'Tabify Guitar TAB',
        Author: 'Tabify',
        Subject: 'Beginner Guitar Tablature',
      },
    });

    const stream = fs.createWriteStream(pdfPath);
    doc.pipe(stream);

    // Title block
    doc.font('Helvetica-Bold').fontSize(TITLE_FONT_SIZE);
    doc.text(meta.title || 'Guitar Tablature', { align: 'center' });

    if (meta.composer) {
      doc.font('Helvetica').fontSize(12);
      doc.text(meta.composer, { align: 'center' });
    }

    doc.moveDown(0.5);
    doc.font('Helvetica').fontSize(9).fillColor('#666666');
    doc.text('Generated by Tabify — Beginner Guitar TAB', { align: 'center' });
    doc.fillColor('#000000');
    doc.moveDown(1.5);

    // TAB content — split into lines to handle page breaks
    doc.font(TAB_FONT).fontSize(TAB_FONT_SIZE);
    const lines = ascii.split('\n');

    for (const line of lines) {
      if (doc.y > doc.page.height - MARGIN - 20) {
        doc.addPage();
      }
      doc.text(line, { lineBreak: false });
    }

    // Fingering legend if present
    const legendStart = ascii.indexOf('/* Fingering Guide */');
    if (legendStart === -1) {
      doc.moveDown(2);
      doc.font('Helvetica').fontSize(8).fillColor('#888888');
      doc.text('© Tabify — For personal practice use', { align: 'center' });
    }

    doc.end();

    stream.on('finish', () => {
      logger.info('PDF export complete', { pdfPath });
      resolve(pdfPath);
    });

    stream.on('error', reject);
  });
}

/**
 * Export TAB as PNG using PDFKit vector rendering to a buffer,
 * then converting via a simple bitmap approach.
 *
 * Since we avoid heavy native deps (canvas/puppeteer), PNG is generated
 * by writing an SVG wrapper and using PDFKit's embedded image pipeline
 * with a pre-rendered SVG-to-PNG conversion via pure JS bitmap.
 *
 * @param {ExportOptions} options
 * @returns {Promise<string>} Path to generated PNG
 */
async function exportToPng(options) {
  const { ascii, meta, jobId } = options;
  const exportDir = path.join(config.paths.outputDir, jobId, 'exports');
  ensureDir(exportDir);

  const pngPath = path.join(exportDir, `${sanitizeFilename(meta.title || 'tabify-tab')}.png`);
  const svgContent = buildTabSvg(ascii, meta);

  // Write SVG file (browsers can open it; we also produce a PNG via simple rasterization)
  const svgPath = path.join(exportDir, 'tab.svg');
  fs.writeFileSync(svgPath, svgContent, 'utf8');

  // Generate PNG using a minimal bitmap encoder (pure JS, no native deps)
  const pngBuffer = rasterizeSvgToPng(svgContent);
  fs.writeFileSync(pngPath, pngBuffer);

  logger.info('PNG export complete', { pngPath });
  return pngPath;
}

/**
 * Build an SVG representation of the TAB for crisp rendering.
 * @param {string} ascii
 * @param {object} meta
 * @returns {string}
 */
function buildTabSvg(ascii, meta) {
  const lines = ascii.split('\n').filter((l) => !l.startsWith('/*'));
  const lineHeight = 22;
  const padding = 40;
  const width = 800;
  const height = padding * 2 + lines.length * lineHeight + 60;

  const title = escapeXml(meta.title || 'Guitar Tablature');
  const composer = meta.composer ? escapeXml(meta.composer) : '';

  const textLines = lines
    .map((line, i) => {
      const y = padding + 60 + i * lineHeight;
      return `<text x="${padding}" y="${y}" font-family="'SF Mono', 'Menlo', 'Courier New', monospace" font-size="14" fill="#1d1d1f">${escapeXml(line)}</text>`;
    })
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">
  <rect width="100%" height="100%" fill="#fafafa"/>
  <rect x="20" y="20" width="${width - 40}" height="${height - 40}" rx="16" fill="#ffffff" stroke="#e5e5ea" stroke-width="1"/>
  <text x="${width / 2}" y="${padding + 10}" text-anchor="middle" font-family="-apple-system, BlinkMacSystemFont, sans-serif" font-size="20" font-weight="600" fill="#1d1d1f">${title}</text>
  ${composer ? `<text x="${width / 2}" y="${padding + 32}" text-anchor="middle" font-family="-apple-system, BlinkMacSystemFont, sans-serif" font-size="13" fill="#86868b">${composer}</text>` : ''}
  ${textLines}
  <text x="${width / 2}" y="${height - 20}" text-anchor="middle" font-family="-apple-system, BlinkMacSystemFont, sans-serif" font-size="10" fill="#aeaeb2">Generated by Tabify</text>
</svg>`;
}

/**
 * Minimal SVG → PNG rasterizer using pure JS.
 * Renders text lines onto an uncompressed PNG bitmap.
 * @param {string} svgContent
 * @returns {Buffer}
 */
function rasterizeSvgToPng(svgContent) {
  // Extract text content from SVG for bitmap rendering
  const textMatches = [...svgContent.matchAll(/<text[^>]*>([^<]*)<\/text>/g)];
  const titleMatch = svgContent.match(/font-size="20"[^>]*>([^<]+)</);

  const width = 800;
  const lineCount = textMatches.length || 10;
  const height = Math.max(400, 80 + lineCount * 22);

  // Build RGBA pixel buffer (white background)
  const pixels = Buffer.alloc(width * height * 4, 255);

  // Draw dark text lines (simplified monospace layout)
  const tabLines = textMatches
    .map((m) => m[1])
    .filter((t) => t.length > 2 && !t.includes('Generated by'));

  const startY = titleMatch ? 90 : 60;
  tabLines.forEach((line, idx) => {
    drawTextLine(pixels, width, height, 40, startY + idx * 22, line, '#1d1d1f');
  });

  if (titleMatch) {
    drawTextLine(pixels, width, height, width / 2 - (titleMatch[1].length * 5), 45, titleMatch[1], '#1d1d1f');
  }

  return encodePng(width, height, pixels);
}

/**
 * Draw a horizontal line of pixels for monospace text (5x7 bitmap font simplified).
 * @param {Buffer} pixels
 * @param {number} width
 * @param {number} height
 * @param {number} x
 * @param {number} y
 * @param {string} text
 * @param {string} color
 */
function drawTextLine(pixels, width, height, x, y, text, color) {
  const [r, g, b] = hexToRgb(color);
  let cursorX = Math.floor(x);

  for (const char of text) {
    const glyph = SIMPLE_GLYPHS[char] || SIMPLE_GLYPHS['?'];
    for (let row = 0; row < 7; row += 1) {
      for (let col = 0; col < 5; col += 1) {
        if (glyph[row] & (1 << (4 - col))) {
          setPixel(pixels, width, height, cursorX + col, y + row, r, g, b, 255);
        }
      }
    }
    cursorX += 6;
  }
}

function setPixel(pixels, width, height, x, y, r, g, b, a) {
  if (x < 0 || y < 0 || x >= width || y >= height) return;
  const idx = (y * width + x) * 4;
  pixels[idx] = r;
  pixels[idx + 1] = g;
  pixels[idx + 2] = b;
  pixels[idx + 3] = a;
}

function hexToRgb(hex) {
  const h = hex.replace('#', '');
  return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)];
}

/**
 * Encode RGBA buffer as PNG (uncompressed, filter type 0).
 * @param {number} width
 * @param {number} height
 * @param {Buffer} rgba
 * @returns {Buffer}
 */
function encodePng(width, height, rgba) {
  const { deflateSync } = require('zlib');

  // Build raw image data with filter byte per row
  const rawRows = Buffer.alloc(height * (1 + width * 4));
  for (let y = 0; y < height; y += 1) {
    const rowStart = y * (1 + width * 4);
    rawRows[rowStart] = 0; // No filter
    rgba.copy(rawRows, rowStart + 1, y * width * 4, (y + 1) * width * 4);
  }

  const compressed = deflateSync(rawRows);
  const signature = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);

  const ihdr = createChunk('IHDR', (() => {
    const buf = Buffer.alloc(13);
    buf.writeUInt32BE(width, 0);
    buf.writeUInt32BE(height, 4);
    buf[8] = 8; // bit depth
    buf[9] = 6; // RGBA
    return buf;
  })());

  const idat = createChunk('IDAT', compressed);
  const iend = createChunk('IEND', Buffer.alloc(0));

  return Buffer.concat([signature, ihdr, idat, iend]);
}

function createChunk(type, data) {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length, 0);
  const typeBuf = Buffer.from(type, 'ascii');
  const combined = Buffer.concat([typeBuf, data]);
  const crc = crc32(combined);
  const crcBuf = Buffer.alloc(4);
  crcBuf.writeUInt32BE(crc >>> 0, 0);
  return Buffer.concat([len, combined, crcBuf]);
}

function crc32(buf) {
  let crc = 0xffffffff;
  for (let i = 0; i < buf.length; i += 1) {
    crc ^= buf[i];
    for (let j = 0; j < 8; j += 1) {
      crc = (crc >>> 1) ^ (crc & 1 ? 0xedb88320 : 0);
    }
  }
  return (crc ^ 0xffffffff) >>> 0;
}

function escapeXml(str) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function sanitizeFilename(name) {
  return name.replace(/[^a-zA-Z0-9-_ ]/g, '').trim().replace(/\s+/g, '-').toLowerCase() || 'tabify-tab';
}

/** Minimal 5x7 bitmap glyphs for TAB characters */
const SIMPLE_GLYPHS = {
  ' ': [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00],
  '-': [0x00, 0x00, 0x00, 0x1f, 0x00, 0x00, 0x00],
  '|': [0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04],
  '/': [0x00, 0x02, 0x04, 0x08, 0x10, 0x00, 0x00],
  '*': [0x00, 0x0a, 0x04, 0x1f, 0x04, 0x0a, 0x00],
  '.': [0x00, 0x00, 0x00, 0x00, 0x00, 0x0c, 0x0c],
  '0': [0x0e, 0x11, 0x13, 0x15, 0x19, 0x11, 0x0e],
  '1': [0x04, 0x0c, 0x04, 0x04, 0x04, 0x04, 0x0e],
  '2': [0x0e, 0x11, 0x01, 0x06, 0x08, 0x10, 0x1f],
  '3': [0x1f, 0x02, 0x04, 0x02, 0x01, 0x11, 0x0e],
  '4': [0x02, 0x06, 0x0a, 0x12, 0x1f, 0x02, 0x02],
  '5': [0x1f, 0x10, 0x1e, 0x01, 0x01, 0x11, 0x0e],
  '6': [0x06, 0x08, 0x10, 0x1e, 0x11, 0x11, 0x0e],
  '7': [0x1f, 0x01, 0x02, 0x04, 0x08, 0x08, 0x08],
  '8': [0x0e, 0x11, 0x11, 0x0e, 0x11, 0x11, 0x0e],
  '9': [0x0e, 0x11, 0x11, 0x0f, 0x01, 0x02, 0x0c],
  'A': [0x0e, 0x11, 0x11, 0x1f, 0x11, 0x11, 0x11],
  'B': [0x1e, 0x11, 0x11, 0x1e, 0x11, 0x11, 0x1e],
  'C': [0x0e, 0x11, 0x10, 0x10, 0x10, 0x11, 0x0e],
  'D': [0x1e, 0x11, 0x11, 0x11, 0x11, 0x11, 0x1e],
  'E': [0x1f, 0x10, 0x10, 0x1e, 0x10, 0x10, 0x1f],
  'F': [0x1f, 0x10, 0x10, 0x1e, 0x10, 0x10, 0x10],
  'G': [0x0e, 0x11, 0x10, 0x17, 0x11, 0x11, 0x0e],
  'H': [0x11, 0x11, 0x11, 0x1f, 0x11, 0x11, 0x11],
  'I': [0x0e, 0x04, 0x04, 0x04, 0x04, 0x04, 0x0e],
  'L': [0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x1f],
  'M': [0x11, 0x1b, 0x15, 0x11, 0x11, 0x11, 0x11],
  'N': [0x11, 0x19, 0x15, 0x13, 0x11, 0x11, 0x11],
  'O': [0x0e, 0x11, 0x11, 0x11, 0x11, 0x11, 0x0e],
  'P': [0x1e, 0x11, 0x11, 0x1e, 0x10, 0x10, 0x10],
  'R': [0x1e, 0x11, 0x11, 0x1e, 0x14, 0x12, 0x11],
  'S': [0x0e, 0x11, 0x10, 0x0e, 0x01, 0x11, 0x0e],
  'T': [0x1f, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04],
  'U': [0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x0e],
  'V': [0x11, 0x11, 0x11, 0x11, 0x0a, 0x0a, 0x04],
  'W': [0x11, 0x11, 0x11, 0x15, 0x15, 0x1b, 0x11],
  'X': [0x11, 0x11, 0x0a, 0x04, 0x0a, 0x11, 0x11],
  'Y': [0x11, 0x11, 0x0a, 0x04, 0x04, 0x04, 0x04],
  'Z': [0x1f, 0x01, 0x02, 0x04, 0x08, 0x10, 0x1f],
  '→': [0x00, 0x04, 0x02, 0x1f, 0x02, 0x04, 0x00],
  '?': [0x0e, 0x11, 0x01, 0x02, 0x04, 0x00, 0x04],
  'e': [0x00, 0x00, 0x0e, 0x11, 0x1f, 0x10, 0x0e],
  'B': [0x1e, 0x11, 0x11, 0x1e, 0x11, 0x11, 0x1e],
  'G': [0x0e, 0x11, 0x10, 0x17, 0x11, 0x11, 0x0e],
};

module.exports = {
  exportToPdf,
  exportToPng,
  buildTabSvg,
  sanitizeFilename,
};
